name: make

# Controls when the action will run:
# https://help.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#filtering-for-specific-branches-tags-and-paths
on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
  - cron: 0 0 1 * * # once a month

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        coq_version:
          - '8.15.0'
          - '8.14.1'
          - '8.13.2'
        ocaml_version: ['4.11.2-flambda']
      max-parallel: 4
      # don't cancel all in-progress jobs if one matrix job fails:
      fail-fast: false
    steps:
    - name: Check out main repo
      uses: actions/checkout@v3
    - name: Check out submodules
      uses: actions/checkout@v3
      with:
          repository: logsem/machine_program_logic
          path: vendor/machine_program_logic
          ref: schedule_cond_frac_agree
          token: ${{ secrets.HYPVERI_ACCESS_TOKEN }}
          persist-credentials: false
    - name: Check out submodules
      uses: actions/checkout@v2
      with:
          repository: logsem/machine_utils
          path: vendor/machine_utils
    - name: Change permissions
      run: chmod a+x disable-qed.sh
    - name: Build
      uses: coq-community/docker-coq-action@v1
      with:
          before_install: |
            startGroup "Add iris repo"
              opam repository add --all-switches --set-default iris-dev https://gitlab.mpi-sws.org/iris/opam.git
            endGroup
          before_script: |
            startGroup "Build project"
              sudo chown -R coq:coq .
              make ci
            endGroup
          ocaml_version: ${{ matrix.ocaml_version }}
          coq_version: ${{ matrix.coq_version }}
          opam_file: './hypveri.opam'
          # custom_image: 'kaptch/coq-iris:latest'
